#include "main.h"
#include "definition.h"

using namespace pros;

Controller master(E_CONTROLLER_MASTER);

Motor  driveBL(2, E_MOTOR_GEARSET_06, 1, E_MOTOR_ENCODER_DEGREES);
Motor  driveBR(9, E_MOTOR_GEARSET_06, 0, E_MOTOR_ENCODER_DEGREES);
Motor  driveFL(1, E_MOTOR_GEARSET_06, 1, E_MOTOR_ENCODER_DEGREES);
Motor driveFR(10, E_MOTOR_GEARSET_06, 0, E_MOTOR_ENCODER_DEGREES);
Motor     lift(4, E_MOTOR_GEARSET_06, 1, E_MOTOR_ENCODER_DEGREES);
Motor    angle(3, E_MOTOR_GEARSET_06, 0, E_MOTOR_ENCODER_DEGREES);
Motor  intakeL(8, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
Motor  intakeR(7, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
