#include "main.h"
#include "definition.h"

using namespace pros;

Controller master(E_CONTROLLER_MASTER);

Motor  transL(2, E_MOTOR_GEARSET_06, 1, E_MOTOR_ENCODER_DEGREES);
Motor  transR(9, E_MOTOR_GEARSET_06, 0, E_MOTOR_ENCODER_DEGREES);
Motor  driveL(1, E_MOTOR_GEARSET_06, 1, E_MOTOR_ENCODER_DEGREES);
Motor driveR(10, E_MOTOR_GEARSET_06, 0, E_MOTOR_ENCODER_DEGREES);
Motor   liftL(4, E_MOTOR_GEARSET_06, 1, E_MOTOR_ENCODER_DEGREES);
Motor   liftR(3, E_MOTOR_GEARSET_06, 0, E_MOTOR_ENCODER_DEGREES);
Motor intakeL(8, E_MOTOR_GEARSET_18, 1, E_MOTOR_ENCODER_DEGREES);
Motor intakeR(7, E_MOTOR_GEARSET_18, 0, E_MOTOR_ENCODER_DEGREES);
